/** Canales de YouTube de inversión. Fuente: suscripciones de Nico (capturas del 2026-10-06) y referencias en inglés comprobadas el mismo día cargando la página del canal. */
export type ChannelCategory = 'inversion' | 'negocio' | 'referencia' | 'empresa';

export type InvestorChannel = {
    name: string;
    handle: string;
    url: string;
    channel_id: string | null;
    category: ChannelCategory;
    language: 'es' | 'en';
    note: string | null;
    source: string;
    checked_at: string;
};

export const CHANNELS_CHECKED_AT = '2026-10-06';
const SUBS = 'Suscripciones de Nico (capturas, 2026-10-06)';
const CHECKED = 'Página del canal cargada el 2026-10-06';

export const INVESTOR_CHANNELS: InvestorChannel[] = [
    {
        name: 'Lunaticoin',
        handle: '@Lunaticoin',
        url: 'https://www.youtube.com/@Lunaticoin',
        channel_id: null,
        category: 'inversion',
        language: 'es',
        note: null,
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Juan Ramón Rallo',
        handle: '@juanrallo',
        url: 'https://www.youtube.com/@juanrallo',
        channel_id: null,
        category: 'inversion',
        language: 'es',
        note: 'Economía',
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Instituto Juan de Mariana',
        handle: '@InstJuandeMariana',
        url: 'https://www.youtube.com/@InstJuandeMariana',
        channel_id: null,
        category: 'inversion',
        language: 'es',
        note: 'Economía',
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Gustavo Martínez',
        handle: '@Gustavo-Bolsa',
        url: 'https://www.youtube.com/@Gustavo-Bolsa',
        channel_id: null,
        category: 'inversion',
        language: 'es',
        note: null,
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Memorias de Pez',
        handle: '@MemoriasDePez',
        url: 'https://www.youtube.com/@MemoriasDePez',
        channel_id: null,
        category: 'inversion',
        language: 'es',
        note: null,
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Negocios TV',
        handle: '@NegociosTV',
        url: 'https://www.youtube.com/@NegociosTV',
        channel_id: null,
        category: 'inversion',
        language: 'es',
        note: null,
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Inversión Racional Podcast',
        handle: '@InversionRacional',
        url: 'https://www.youtube.com/@InversionRacional',
        channel_id: null,
        category: 'inversion',
        language: 'es',
        note: null,
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Jose Luis Cava (Bolsacava)',
        handle: '@JoseLuisCavatv',
        url: 'https://www.youtube.com/@JoseLuisCavatv',
        channel_id: null,
        category: 'inversion',
        language: 'es',
        note: 'Título del canal en YouTube: Jose Luis Cava',
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'SpaceMobile Now',
        handle: '@SpaceMobileNow',
        url: 'https://www.youtube.com/@SpaceMobileNow',
        channel_id: null,
        category: 'inversion',
        language: 'en',
        note: 'Tema AST SpaceMobile',
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'AST SpaceMobile Podcast',
        handle: '@ASTSpaceMobilePodcast',
        url: 'https://www.youtube.com/@ASTSpaceMobilePodcast',
        channel_id: null,
        category: 'inversion',
        language: 'en',
        note: 'Tema AST SpaceMobile; comunidad, no verificado como oficial de la empresa',
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Locos de Wall Street',
        handle: '@locosdewallstreet',
        url: 'https://www.youtube.com/@locosdewallstreet',
        channel_id: null,
        category: 'inversion',
        language: 'es',
        note: null,
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Javier DV - Inversión y Finanzas',
        handle: '@JavierDV',
        url: 'https://www.youtube.com/@JavierDV',
        channel_id: null,
        category: 'inversion',
        language: 'es',
        note: null,
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Aria Radnia',
        handle: '@QualityInvest5',
        url: 'https://www.youtube.com/@QualityInvest5',
        channel_id: null,
        category: 'inversion',
        language: 'en',
        note: 'Quality investing',
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Sourcery with Molly O\'Shea',
        handle: '@SourceryVC',
        url: 'https://www.youtube.com/@SourceryVC',
        channel_id: null,
        category: 'negocio',
        language: 'en',
        note: 'Capital riesgo y tecnología',
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'The Diary Of A CEO',
        handle: '@TheDiaryOfACEO',
        url: 'https://www.youtube.com/@TheDiaryOfACEO',
        channel_id: null,
        category: 'negocio',
        language: 'en',
        note: 'Entrevistas de negocio; generalista',
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Bloomberg Television',
        handle: '@markets',
        url: 'https://www.youtube.com/@markets',
        channel_id: 'UCIALMKvObZNtJ6AmdCLP7Lg',
        category: 'referencia',
        language: 'en',
        note: null,
        source: CHECKED,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'CNBC Television',
        handle: '@CNBCtelevision',
        url: 'https://www.youtube.com/@CNBCtelevision',
        channel_id: 'UCrp_UI8XtuYfpiqluWLD7Lw',
        category: 'referencia',
        language: 'en',
        note: null,
        source: CHECKED,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Yahoo Finance',
        handle: '@YahooFinance',
        url: 'https://www.youtube.com/@YahooFinance',
        channel_id: 'UCEAZeUIeJs0IjQiqTCdVSIg',
        category: 'referencia',
        language: 'en',
        note: null,
        source: CHECKED,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Patrick Boyle',
        handle: '@PatrickBoyle',
        url: 'https://www.youtube.com/@PatrickBoyle',
        channel_id: 'UCOIi9OLSpXRsX-wp2u26fsA',
        category: 'referencia',
        language: 'en',
        note: null,
        source: CHECKED,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'The Plain Bagel',
        handle: '@ThePlainBagel',
        url: 'https://www.youtube.com/@ThePlainBagel',
        channel_id: 'UCFCEuCsyWP0YkP3CZ3Mr01Q',
        category: 'referencia',
        language: 'en',
        note: null,
        source: CHECKED,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Aswath Damodaran',
        handle: '@AswathDamodaranonValuation',
        url: 'https://www.youtube.com/@AswathDamodaranonValuation',
        channel_id: 'UCLvnJL8htRR1T9cbSccaoVw',
        category: 'referencia',
        language: 'en',
        note: 'Probable canal oficial: su web de NYU no enlaza YouTube',
        source: CHECKED,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Warren Buffett Archive',
        handle: '@WarrenBuffettArchive',
        url: 'https://www.youtube.com/@WarrenBuffettArchive',
        channel_id: 'UCyMGOTSE13Uf9Big_Ppj8Wg',
        category: 'referencia',
        language: 'en',
        note: 'Sugerido; probable oficial (archivo de CNBC)',
        source: CHECKED,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Talks at Google',
        handle: '@TalksAtGoogle',
        url: 'https://www.youtube.com/@TalksAtGoogle',
        channel_id: 'UCbmNph6atAoGfqLoCL_duAg',
        category: 'referencia',
        language: 'en',
        note: 'Sugerido',
        source: CHECKED,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Numantia (Emérito Quintana)',
        handle: '@emeritoquintana',
        url: 'https://www.youtube.com/@emeritoquintana',
        channel_id: null,
        category: 'inversion',
        language: 'es',
        note: 'Enlazado desde la web oficial de Numantia',
        source: 'https://www.numantiapatrimonio.com/ (web oficial de Numantia)',
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Tesla',
        handle: '@tesla',
        url: 'https://www.youtube.com/@tesla',
        channel_id: null,
        category: 'empresa',
        language: 'en',
        note: null,
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Meta',
        handle: '@meta',
        url: 'https://www.youtube.com/@meta',
        channel_id: null,
        category: 'empresa',
        language: 'en',
        note: null,
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Brookfield',
        handle: '@brookfieldcorporation',
        url: 'https://www.youtube.com/@brookfieldcorporation',
        channel_id: null,
        category: 'empresa',
        language: 'en',
        note: null,
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'ServiceNow',
        handle: '@servicenow',
        url: 'https://www.youtube.com/@servicenow',
        channel_id: null,
        category: 'empresa',
        language: 'en',
        note: null,
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
    {
        name: 'Vodafone Group',
        handle: '@VodafoneGroup',
        url: 'https://www.youtube.com/@VodafoneGroup',
        channel_id: null,
        category: 'empresa',
        language: 'en',
        note: null,
        source: SUBS,
        checked_at: CHANNELS_CHECKED_AT,
    },
];
