import Link from 'next/link';
import { ArrowLeft, Check, RefreshCcw, X } from 'lucide-react';

import { MutationForm } from '@/components/forms/MutationForm';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { decideDecisionLesson, getDecisionLessons, proposeDecisionLessons, updateDecisionLesson } from '@/lib/actions/research-tools.actions';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export default async function DecisionLessonsPage({ params }: { params: Promise<{ ticker: string }> }) {
  const ticker = (await params).ticker.toUpperCase();
  const { lessons, taxonomy } = await getDecisionLessons(ticker);
  return <main className="mx-auto flex max-w-7xl flex-col gap-6"><header className="flex flex-col gap-4 border-b border-gray-800 pb-5 md:flex-row md:items-end"><div><Button asChild className="mb-4" size="sm" variant="ghost"><Link href={`/research/${ticker}`}><ArrowLeft className="h-4 w-4" />{ticker} workspace</Link></Button><p className="text-sm font-semibold uppercase text-teal-300">Decision learning</p><h1 className="mt-1 text-3xl font-bold text-gray-100">Decision Lessons</h1><p className="mt-2 text-sm text-gray-400">Turn forecast misses into reviewed lessons without allowing auto-generated conclusions to become canonical silently.</p></div><MutationForm action={proposeDecisionLessons.bind(null, ticker)} className="md:ml-auto" successMessage="Lessons proposed"><Button type="submit"><RefreshCcw className="h-4 w-4" />Propose from misses</Button></MutationForm></header>
    <section className="grid gap-5">{lessons.map((item) => <article className="rounded-xl border border-gray-800 bg-[#101010] p-5" key={item.id}><div className="flex flex-wrap items-center gap-2"><Badge className={item.status === 'approved' ? 'border-teal-800 text-teal-300' : item.status === 'rejected' ? 'border-red-900 text-red-300' : 'border-amber-900 text-amber-300'} variant="outline">{item.status}</Badge><Badge variant="outline">{item.taxonomy}</Badge><span className="text-xs text-gray-500">Lesson #{item.id} · decision #{item.decision_journal_entry_id ?? 'unlinked'} · review #{item.expectation_review_id ?? 'n/a'}</span></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-lg border border-gray-800 p-3"><div className="text-xs font-semibold uppercase text-gray-500">Expectation</div><p className="mt-2 text-sm text-gray-300">{item.expectation}</p></div><div className="rounded-lg border border-gray-800 p-3"><div className="text-xs font-semibold uppercase text-gray-500">Outcome</div><p className="mt-2 text-sm text-gray-300">{item.outcome}</p></div><div className="rounded-lg border border-gray-800 p-3"><div className="text-xs font-semibold uppercase text-gray-500">Deviation</div><p className="mt-2 text-sm text-gray-300">{item.deviation}</p></div></div>
      {item.status === 'approved' ? <div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-lg border border-teal-900/40 bg-teal-950/10 p-4"><div className="text-xs font-semibold uppercase text-teal-400">Approved lesson</div><p className="mt-2 text-sm leading-6 text-gray-200">{item.lesson}</p></div><div className="rounded-lg border border-gray-800 p-4"><div className="text-xs font-semibold uppercase text-gray-500">Future application</div><p className="mt-2 text-sm leading-6 text-gray-300">{item.future_application}</p></div></div> : <MutationForm action={updateDecisionLesson.bind(null, ticker, item.id)} className="mt-4 grid gap-3" successMessage="Lesson updated"><select className="h-9 rounded-md border border-gray-800 bg-black px-3 text-sm text-gray-200" defaultValue={item.taxonomy} name="taxonomy">{taxonomy.map((value) => <option key={value}>{value}</option>)}</select><div className="grid gap-3 md:grid-cols-2"><Textarea defaultValue={item.cause} name="cause" placeholder="Root cause" required /><Textarea defaultValue={item.error} name="error" placeholder="Decision error" required /><Textarea defaultValue={item.lesson} name="lesson" placeholder="Durable lesson" required /><Textarea defaultValue={item.future_application} name="future_application" placeholder="How this changes future decisions" required /></div><Button className="w-fit" type="submit">Save analyst review</Button></MutationForm>}
      {item.status === 'proposed' ? <div className="mt-4 flex gap-2"><MutationForm action={decideDecisionLesson.bind(null, ticker, item.id, 'approve')} successMessage="Lesson approved"><Button type="submit" size="sm"><Check className="h-4 w-4" />Approve</Button></MutationForm><MutationForm action={decideDecisionLesson.bind(null, ticker, item.id, 'reject')} successMessage="Lesson rejected"><Button type="submit" size="sm" variant="outline"><X className="h-4 w-4" />Reject</Button></MutationForm></div> : null}</article>)}{!lessons.length ? <div className="rounded-xl border border-dashed border-gray-800 p-8 text-center text-sm text-gray-500">No decision lessons yet. Review forecast outcomes, then propose lessons from misses.</div> : null}</section>
  </main>;
}
