import Link from 'next/link';
import { ArrowLeft, AlertTriangle } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { getPortfolioIntelligence } from '@/lib/actions/research-tools.actions';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

function pct(value: number | null) { return value === null ? 's/d' : `${(value * 100).toFixed(1)}%`; }
function ratio(value: number | null) { return value === null ? 's/d' : value.toFixed(2); }

function Exposure({ title, values }: { title: string; values: Record<string, number> }) {
  const rows = Object.entries(values).sort((a, b) => b[1] - a[1]);
  return <section className="rounded-xl border border-gray-800 bg-[#101010] p-5"><h2 className="font-semibold text-gray-100">{title}</h2><div className="mt-4 grid gap-3">{rows.map(([label, value]) => <div key={label}><div className="mb-1 flex justify-between text-sm"><span className="text-gray-300">{label}</span><span className="text-gray-500">{pct(value)}</span></div><div className="h-2 overflow-hidden rounded bg-gray-900"><div className="h-full rounded bg-teal-600" style={{ width: `${Math.min(100, value * 100)}%` }} /></div></div>)}{!rows.length ? <p className="text-sm text-gray-500">Sin datos de exposición.</p> : null}</div></section>;
}

export default async function PortfolioIntelligencePage({ searchParams }: { searchParams: Promise<{ years?: string }> }) {
  const query = await searchParams;
  const years = Math.max(1, Math.min(20, Number(query.years) || 5));
  const data = await getPortfolioIntelligence(years);
  const tickers = Object.keys(data.risk.correlations);
  return <main id="content" tabIndex={-1} className="mx-auto flex max-w-7xl flex-col gap-6"><header className="flex flex-col gap-4 border-b border-gray-800 pb-5 md:flex-row md:items-end"><div><Button asChild className="mb-4" size="sm" variant="ghost"><Link href="/portfolio"><ArrowLeft className="h-4 w-4" />Cartera</Link></Button><p className="text-sm font-semibold uppercase text-teal-300">Rendimiento y riesgo</p><h1 className="mt-1 text-3xl font-bold text-gray-100">Inteligencia de cartera</h1><p className="mt-2 text-sm text-gray-400">Analítica de cartera indicativa con cobertura de datos y limitaciones metodológicas explícitas.</p></div><form className="flex gap-2 md:ml-auto" method="get"><Input className="w-24" max="20" min="1" name="years" defaultValue={years} type="number" /><Button type="submit">Años</Button></form></header>
    <section className={`rounded-xl border p-4 ${data.performance.twr_is_exact ? 'border-teal-900/60 bg-teal-950/20' : 'border-amber-900/60 bg-amber-950/20'}`}><div className="flex items-start gap-3"><AlertTriangle className={`mt-0.5 h-5 w-5 shrink-0 ${data.performance.twr_is_exact ? 'text-teal-300' : 'text-amber-300'}`} /><div><h2 className={`font-semibold ${data.performance.twr_is_exact ? 'text-teal-200' : 'text-amber-200'}`}>{data.performance.twr_is_exact ? 'TWR diario basado en snapshots' : 'Indicativo: no es rendimiento contable exacto'}</h2><p className="mt-1 text-sm leading-6 text-gray-400">{data.performance.twr_is_exact ? `El TWR enlaza ${data.coverage.snapshot_returns} retornos diarios completos con posiciones, caja, FX y flujos externos persistidos.` : 'El TWR usa pesos estáticos actuales hasta que existan snapshots diarios completos de posiciones y caja.'} La atribución sigue siendo heurística, no por lotes de transacciones ni tipo Brinson.</p></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[data.performance.twr_is_exact ? 'TWR diario' : 'TWR indicativo', pct(data.performance.twr)], ['XIRR', pct(data.performance.xirr)], ['Anualizado', pct(data.performance.annualized_return)], ['Máx. caída', pct(data.risk.max_drawdown)], ['Volatilidad', pct(data.risk.volatility)], ['Sharpe', ratio(data.risk.sharpe)], ['Sortino', ratio(data.risk.sortino)], ['VaR 95%', pct(data.risk.var_95)], ['CVaR 95%', pct(data.risk.cvar_95)], ['Calmar', ratio(data.risk.calmar)], ['Beta', ratio(data.risk.beta)]].map(([label, value]) => <div className="rounded-xl border border-gray-800 bg-[#101010] p-4" key={label}><div className="text-xs font-semibold uppercase text-gray-500">{label}</div><div className="mt-2 text-2xl font-semibold text-gray-100">{value}</div></div>)}</section>
    <section className="grid gap-6 lg:grid-cols-3"><Exposure title="Concentración por posición" values={data.concentration.weights} /><Exposure title="Sectores" values={data.exposures.sectors} /><Exposure title="Países" values={data.exposures.countries} /><Exposure title="Divisas" values={data.exposures.currencies} /><Exposure title="Factores" values={data.exposures.factors} /><section className="rounded-xl border border-gray-800 bg-[#101010] p-5"><h2 className="font-semibold text-gray-100">Concentración</h2><div className="mt-4 grid gap-3 text-sm"><div className="flex justify-between"><span>Top 1</span><span className="text-gray-200">{pct(data.concentration.top_1)}</span></div><div className="flex justify-between"><span>Top 5</span><span className="text-gray-200">{pct(data.concentration.top_5)}</span></div><div className="flex justify-between"><span>Herfindahl</span><span className="text-gray-200">{data.concentration.herfindahl.toFixed(3)}</span></div><div className="mt-2 border-t border-gray-800 pt-3 text-gray-500">{data.coverage.positions === 0 ? 'Sin posiciones que valorar todavía.' : `${data.coverage.positions_with_price_history}/${data.coverage.positions} posiciones con histórico de precios (${data.coverage.price_history_percent.toFixed(0)}%)`}</div></div></section></section>
    <section className="rounded-xl border border-gray-800 bg-[#101010] p-5"><div className="flex flex-col gap-2 md:flex-row md:items-center"><h2 className="font-semibold text-gray-100">Comparativa con benchmark ({data.benchmark.symbol})</h2>{data.benchmark.status !== 'calculated' ? <Badge className="md:ml-auto" variant="outline">{data.benchmark.status === 'missing_benchmark' ? 'benchmark sin ingerir' : `solapamiento insuficiente (${data.benchmark.observations} días)`}</Badge> : null}</div>{data.benchmark.status === 'calculated' ? <section className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Cartera anualizada', pct(data.benchmark.portfolio_annualized)], [`${data.benchmark.symbol} anualizado`, pct(data.benchmark.benchmark_annualized)], ['Alpha', pct(data.benchmark.alpha_annualized)], ['Error de seguimiento', pct(data.benchmark.tracking_error)], ['Ratio de información', ratio(data.benchmark.information_ratio)], ['Observaciones', String(data.benchmark.observations)]].map(([label, value]) => <div className="rounded-xl border border-gray-800 bg-gray-900/40 p-4" key={label}><div className="text-xs font-semibold uppercase text-gray-500">{label}</div><div className="mt-2 text-xl font-semibold text-gray-100">{value}</div></div>)}</section> : <p className="mt-3 text-sm text-gray-400">La comparativa con benchmark necesita la serie de precios de SPY ingerida vía refresco de mercado y al menos 20 sesiones compartidas con la serie de retornos de la cartera.</p>}</section>
    <section className="rounded-xl border border-gray-800 bg-[#101010] p-5"><div className="flex flex-col gap-2 md:flex-row md:items-center"><h2 className="font-semibold text-gray-100">Contribución por posición</h2><Badge className="md:ml-auto" variant="outline">{data.ledger_contribution.coverage.positions === 0 ? 'sin posiciones' : `${data.ledger_contribution.coverage.with_contribution}/${data.ledger_contribution.coverage.positions} posiciones valoradas al inicio del horizonte`}</Badge></div><p className="mt-2 text-xs text-gray-500">Plusvalías + plus latentes + ingresos por posición a partir del registro completo de transacciones ({data.ledger_contribution.methodology}){data.ledger_contribution.base_currency ? `, en ${data.ledger_contribution.base_currency}` : ''}. Contribución = valor final − valor inicial − neto invertido + ingresos. Los pesos firmados muestran ganadores por encima del 100 % y detractores en negativo.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs uppercase text-gray-500"><tr><th className="border-b border-gray-800 py-2">Ticker</th><th className="border-b border-gray-800 py-2 text-right">Valor inicial</th><th className="border-b border-gray-800 py-2 text-right">Valor final</th><th className="border-b border-gray-800 py-2 text-right">Neto invertido</th><th className="border-b border-gray-800 py-2 text-right">Ingresos</th><th className="border-b border-gray-800 py-2 text-right">P&L</th><th className="border-b border-gray-800 py-2 text-right">Peso</th></tr></thead><tbody>{data.ledger_contribution.positions.map((row) => <tr className="border-b border-gray-900" key={row.ticker}><td className="py-3 font-semibold text-teal-300">{row.ticker}</td><td className="py-3 text-right">{row.start_value.toFixed(0)}</td><td className="py-3 text-right">{row.end_value.toFixed(0)}</td><td className="py-3 text-right">{row.net_invested.toFixed(0)}</td><td className="py-3 text-right">{row.income.toFixed(0)}</td><td className="py-3 text-right">{row.contribution_pnl === null ? `s/d (${row.reason})` : row.contribution_pnl.toFixed(0)}</td><td className="py-3 text-right">{pct(row.contribution_share)}</td></tr>)}</tbody></table></div>{data.ledger_contribution.total_pnl !== null ? <p className="mt-3 text-sm text-gray-400">P&L total del horizonte: <span className="font-semibold text-gray-100">{data.ledger_contribution.total_pnl.toFixed(0)} {data.ledger_contribution.base_currency}</span></p> : null}</section>
    <section className="rounded-xl border border-gray-800 bg-[#101010] p-5"><div className="flex flex-col gap-2 md:flex-row md:items-center"><h2 className="font-semibold text-gray-100">Atribución de retorno heurística</h2><Badge className="md:ml-auto" variant="outline">no es atribución contable</Badge></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="text-xs uppercase text-gray-500"><tr><th className="border-b border-gray-800 py-2">Ticker</th><th className="border-b border-gray-800 py-2 text-right">Peso</th><th className="border-b border-gray-800 py-2 text-right">Retorno total</th>{Object.keys(data.attribution.portfolio_components).map((key) => <th className="border-b border-gray-800 py-2 text-right" key={key}>{key.replaceAll('_', ' ')}</th>)}</tr></thead><tbody>{data.attribution.positions.map((row) => <tr className="border-b border-gray-900" key={row.ticker}><td className="py-3 font-semibold text-teal-300">{row.ticker}</td><td className="py-3 text-right">{pct(row.weight)}</td><td className="py-3 text-right">{pct(row.total_return)}</td>{Object.keys(data.attribution.portfolio_components).map((key) => <td className="py-3 text-right text-gray-400" key={key}>{pct(row.components[key] ?? null)}</td>)}</tr>)}</tbody></table></div></section>
    <section className="rounded-xl border border-gray-800 bg-[#101010] p-5"><h2 className="font-semibold text-gray-100">Correlaciones de retornos</h2><div className="mt-4 overflow-x-auto"><table className="text-sm"><thead><tr><th className="p-2" />{tickers.map((ticker) => <th className="p-2 text-gray-400" key={ticker}>{ticker}</th>)}</tr></thead><tbody>{tickers.map((left) => <tr key={left}><th className="p-2 text-left text-gray-400">{left}</th>{tickers.map((right) => { const correlation = data.risk.correlations[left]?.[right]; return <td className="min-w-16 border border-gray-900 p-2 text-center text-gray-300" key={right} style={{ backgroundColor: correlation === null || correlation === undefined ? 'transparent' : correlation >= 0 ? `rgb(13 148 136 / ${Math.abs(correlation) * 0.35})` : `rgb(239 68 68 / ${Math.abs(correlation) * 0.35})` }}>{correlation === null || correlation === undefined ? '—' : correlation.toFixed(2)}</td>; })}</tr>)}</tbody></table></div></section>
  </main>;
}
