import Link from 'next/link';
import { ArrowLeft, AlertTriangle } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { getPortfolioIntelligence } from '@/lib/actions/research-tools.actions';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

function pct(value: number | null) { return value === null ? 'n/a' : `${(value * 100).toFixed(1)}%`; }
function ratio(value: number | null) { return value === null ? 'n/a' : value.toFixed(2); }

function Exposure({ title, values }: { title: string; values: Record<string, number> }) {
  const rows = Object.entries(values).sort((a, b) => b[1] - a[1]);
  return <section className="rounded-xl border border-gray-800 bg-[#101010] p-5"><h2 className="font-semibold text-gray-100">{title}</h2><div className="mt-4 grid gap-3">{rows.map(([label, value]) => <div key={label}><div className="mb-1 flex justify-between text-sm"><span className="text-gray-300">{label}</span><span className="text-gray-500">{pct(value)}</span></div><div className="h-2 overflow-hidden rounded bg-gray-900"><div className="h-full rounded bg-teal-600" style={{ width: `${Math.min(100, value * 100)}%` }} /></div></div>)}{!rows.length ? <p className="text-sm text-gray-500">No exposure data.</p> : null}</div></section>;
}

export default async function PortfolioIntelligencePage({ searchParams }: { searchParams: Promise<{ years?: string }> }) {
  const query = await searchParams;
  const years = Math.max(1, Math.min(20, Number(query.years) || 5));
  const data = await getPortfolioIntelligence(years);
  const tickers = Object.keys(data.risk.correlations);
  return <main className="mx-auto flex max-w-7xl flex-col gap-6"><header className="flex flex-col gap-4 border-b border-gray-800 pb-5 md:flex-row md:items-end"><div><Button asChild className="mb-4" size="sm" variant="ghost"><Link href="/portfolio"><ArrowLeft className="h-4 w-4" />Portfolio</Link></Button><p className="text-sm font-semibold uppercase text-teal-300">Performance and risk</p><h1 className="mt-1 text-3xl font-bold text-gray-100">Portfolio Intelligence</h1><p className="mt-2 text-sm text-gray-400">Indicative portfolio analytics with explicit data coverage and methodology limitations.</p></div><form className="flex gap-2 md:ml-auto" method="get"><Input className="w-24" max="20" min="1" name="years" defaultValue={years} type="number" /><Button type="submit">Years</Button></form></header>
    <section className={`rounded-xl border p-4 ${data.performance.twr_is_exact ? 'border-teal-900/60 bg-teal-950/20' : 'border-amber-900/60 bg-amber-950/20'}`}><div className="flex items-start gap-3"><AlertTriangle className={`mt-0.5 h-5 w-5 shrink-0 ${data.performance.twr_is_exact ? 'text-teal-300' : 'text-amber-300'}`} /><div><h2 className={`font-semibold ${data.performance.twr_is_exact ? 'text-teal-200' : 'text-amber-200'}`}>{data.performance.twr_is_exact ? 'Snapshot-based daily TWR' : 'Indicative, not exact accounting performance'}</h2><p className="mt-1 text-sm leading-6 text-gray-400">{data.performance.twr_is_exact ? `TWR links ${data.coverage.snapshot_returns} complete daily snapshot returns with persisted position, cash, FX and external-flow inputs.` : 'TWR uses static current weights until complete daily position and cash snapshots exist.'} Attribution remains heuristic rather than transaction-lot or Brinson attribution.</p></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[data.performance.twr_is_exact ? 'Daily TWR' : 'Indicative TWR', pct(data.performance.twr)], ['XIRR', pct(data.performance.xirr)], ['Annualized', pct(data.performance.annualized_return)], ['Max drawdown', pct(data.risk.max_drawdown)], ['Volatility', pct(data.risk.volatility)], ['Sharpe', ratio(data.risk.sharpe)], ['Sortino', ratio(data.risk.sortino)], ['Beta', ratio(data.risk.beta)]].map(([label, value]) => <div className="rounded-xl border border-gray-800 bg-[#101010] p-4" key={label}><div className="text-xs font-semibold uppercase text-gray-500">{label}</div><div className="mt-2 text-2xl font-semibold text-gray-100">{value}</div></div>)}</section>
    <section className="grid gap-6 lg:grid-cols-3"><Exposure title="Position concentration" values={data.concentration.weights} /><Exposure title="Sectors" values={data.exposures.sectors} /><Exposure title="Countries" values={data.exposures.countries} /><Exposure title="Currencies" values={data.exposures.currencies} /><Exposure title="Factors" values={data.exposures.factors} /><section className="rounded-xl border border-gray-800 bg-[#101010] p-5"><h2 className="font-semibold text-gray-100">Concentration</h2><div className="mt-4 grid gap-3 text-sm"><div className="flex justify-between"><span>Top 1</span><span className="text-gray-200">{pct(data.concentration.top_1)}</span></div><div className="flex justify-between"><span>Top 5</span><span className="text-gray-200">{pct(data.concentration.top_5)}</span></div><div className="flex justify-between"><span>Herfindahl</span><span className="text-gray-200">{data.concentration.herfindahl.toFixed(3)}</span></div><div className="mt-2 border-t border-gray-800 pt-3 text-gray-500">{data.coverage.positions_with_price_history}/{data.coverage.positions} positions with price history ({data.coverage.price_history_percent.toFixed(0)}%)</div></div></section></section>
    <section className="rounded-xl border border-gray-800 bg-[#101010] p-5"><div className="flex flex-col gap-2 md:flex-row md:items-center"><h2 className="font-semibold text-gray-100">Heuristic return attribution</h2><Badge className="md:ml-auto" variant="outline">not accounting attribution</Badge></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="text-xs uppercase text-gray-500"><tr><th className="border-b border-gray-800 py-2">Ticker</th><th className="border-b border-gray-800 py-2 text-right">Weight</th><th className="border-b border-gray-800 py-2 text-right">Total return</th>{Object.keys(data.attribution.portfolio_components).map((key) => <th className="border-b border-gray-800 py-2 text-right" key={key}>{key.replaceAll('_', ' ')}</th>)}</tr></thead><tbody>{data.attribution.positions.map((row) => <tr className="border-b border-gray-900" key={row.ticker}><td className="py-3 font-semibold text-teal-300">{row.ticker}</td><td className="py-3 text-right">{pct(row.weight)}</td><td className="py-3 text-right">{pct(row.total_return)}</td>{Object.keys(data.attribution.portfolio_components).map((key) => <td className="py-3 text-right text-gray-400" key={key}>{pct(row.components[key] ?? null)}</td>)}</tr>)}</tbody></table></div></section>
    <section className="rounded-xl border border-gray-800 bg-[#101010] p-5"><h2 className="font-semibold text-gray-100">Return correlations</h2><div className="mt-4 overflow-x-auto"><table className="text-sm"><thead><tr><th className="p-2" />{tickers.map((ticker) => <th className="p-2 text-gray-400" key={ticker}>{ticker}</th>)}</tr></thead><tbody>{tickers.map((left) => <tr key={left}><th className="p-2 text-left text-gray-400">{left}</th>{tickers.map((right) => { const correlation = data.risk.correlations[left]?.[right]; return <td className="min-w-16 border border-gray-900 p-2 text-center text-gray-300" key={right} style={{ backgroundColor: correlation === null || correlation === undefined ? 'transparent' : correlation >= 0 ? `rgb(13 148 136 / ${Math.abs(correlation) * 0.35})` : `rgb(239 68 68 / ${Math.abs(correlation) * 0.35})` }}>{correlation === null || correlation === undefined ? '—' : correlation.toFixed(2)}</td>; })}</tr>)}</tbody></table></div></section>
  </main>;
}
