WORKFLOW_CATALOG = [
    {
        "name": "GenerateThesisWorkflow",
        "input": "ticker",
        "steps": [
            "resolve_ticker",
            "load_company_master",
            "fetch_SEC/FMP/IR/GDELT",
            "store_raw_documents",
            "extract_text_and_tables",
            "chunk_documents",
            "embed_to_Qdrant",
            "normalize_financial_facts",
            "build_historical_model",
            "select_valuation_method",
            "generate_assumptions",
            "run_python_valuation",
            "run_reverse_dcf",
            "analyze_calls",
            "detect_catalysts",
            "red_team",
            "source_audit",
            "write_thesis",
            "save_thesis_version",
            "trace_to_langfuse",
        ],
    },
    {
        "name": "DailyResearchWorkflow",
        "input": "portfolio",
        "steps": [
            "sync_IBKR",
            "fetch_news_for_24_companies",
            "deduplicate_news",
            "classify_materiality",
            "extract_claims",
            "link_to_thesis",
            "create_alerts",
            "generate_daily_brief",
            "update_risk_dashboard",
            "trace_to_langfuse",
        ],
    },
    {
        "name": "ManualNewsWorkflow",
        "input": "pasted_news",
        "steps": [
            "detect_ticker",
            "summarize",
            "extract_claims",
            "classify_event",
            "retrieve_current_thesis",
            "retrieve_assumptions",
            "retrieve_evidence",
            "assess_impact",
            "propose_update",
            "ask_for_approval",
            "save_or_discard",
        ],
    },
    {
        "name": "EarningsWorkflow",
        "input": "ticker + earnings docs",
        "steps": [
            "ingest_earnings_release",
            "extract_reported_numbers",
            "reconcile_SEC/FMP/company_release",
            "compare_vs_previous_period",
            "extract_guidance",
            "analyze_call",
            "update_management_claim_tracker",
            "update_assumptions",
            "rerun_valuation",
            "red_team",
            "source_audit",
            "generate_thesis_diff",
            "save_new_version",
        ],
    },
    {
        "name": "ChatWorkflow",
        "input": "user_question",
        "steps": [
            "classify_scope",
            "detect_ticker/company/portfolio",
            "retrieve_structured_data",
            "retrieve_documents",
            "retrieve_latest_thesis",
            "call_python_tools_if_needed",
            "answer_with_sources",
            "propose_actions_if_relevant",
            "trace_to_langfuse",
        ],
    },
    {
        "name": "RedTeamWorkflow",
        "input": "ticker",
        "steps": [
            "load_current_thesis",
            "load_supporting_and_contradictory_evidence",
            "check_unsupported_material_claims",
            "compare_ROIC_vs_WACC",
            "analyze_moat_and_peers",
            "attack_assumptions",
            "build_strongest_bear_case",
            "define_falsification_tests",
            "create_review_and_alert",
        ],
    },
    {
        "name": "ContradictionWorkflow",
        "input": "ticker + document/news",
        "steps": [
            "extract_material_statements",
            "retrieve_similar_historical_claims",
            "classify_relation",
            "apply_source_hierarchy",
            "create_evidence_suggestions",
            "update_claim_state",
            "create_review_and_alert",
        ],
    },
]

