WORKFLOW_CATALOG = [
    {
        "name": "ThesisShadowComparisonWorkflow",
        "implementation_status": "implemented",
        "truth": "POST /run executes the 6b shadow comparison: runs the LangGraph thesis skeleton under a checkpointer (control state only), verifies node order + idempotent retry, maps classic THESIS_PHASES to graph nodes, and records divergences in a durable WorkflowRun. The classic ThesisService path remains the source of truth; the shadow never mutates domain artifacts.",
        "execution_mode": "shadow",
        "input": "ticker",
        "steps": [
            "run_graph_shadow",
            "verify_idempotent_retry",
            "map_classic_phases",
            "compare_status_semantics",
            "persist_comparison",
        ],
    },
    {
        "name": "ThesisApprovalWorkflow",
        "implementation_status": "implemented",
        "truth": "POST /run executes the 6a thesis graph skeleton under a durable checkpointer until the real 6c approval_gate interrupt and returns thread_id + approval payload (status awaiting_approval). POST /decide resumes the same thread with approve/request_changes; approve routes to publish, request_changes ends the run as changes_requested. Artifacts are still skeleton references - no domain publish happens yet, and the classic ThesisService path remains the source of truth.",
        "execution_mode": "pilot",
        "input": "ticker",
        "steps": [
            "run_until_approval_gate",
            "persist_checkpoint",
            "await_human_decision",
            "resume_with_decision",
        ],
    },
    {
        "name": "GenerateThesisWorkflow",
        "implementation_status": "partial",
        "truth": "POST /run ejecuta ThesisService.generate() sincrono en UNA transaccion; la lista de pasos describe fases internas, no pasos ejecutados separados. Sin resume a mitad de flujo. Langfuse: shadow tracing opcional (flag LANGFUSE_ENABLED), solo metadatos, nunca fuente de verdad.",
        "execution_mode": "deterministic",
        "input": "ticker",
        "steps": [
            "resolve_ticker",
            "load_company_master",
            "fetch_SEC/FMP/IR/GDELT",
            "store_raw_documents",
            "extract_text_and_tables",
            "chunk_documents",
            "embed_to_Qdrant",
            "normalize_financial_facts",
            "build_historical_model",
            "select_valuation_method",
            "generate_assumptions",
            "run_python_valuation",
            "run_reverse_dcf",
            "analyze_calls",
            "detect_catalysts",
            "red_team",
            "source_audit",
            "write_thesis",
            "save_thesis_version",
        ],
    },
    {
        "name": "DailyResearchWorkflow",
        "implementation_status": "partial",
        "truth": "POST /run solo ingiere news_items via NewsService; el resto de pasos corren via scheduler/Dramatiq, no por este endpoint. Langfuse: shadow tracing opcional via run envelope, solo metadatos.",
        "execution_mode": "deterministic",
        "input": "portfolio",
        "steps": [
            "sync_IBKR",
            "fetch_news_for_24_companies",
            "deduplicate_news",
            "classify_materiality",
            "extract_claims",
            "link_to_thesis",
            "create_alerts",
            "generate_daily_brief",
            "update_risk_dashboard",
        ],
    },
    {
        "name": "ManualNewsWorkflow",
        "implementation_status": "descriptive",
        "truth": "Sin ruta de ejecucion en la API; describe el flujo conceptual de noticias manuales.",
        "execution_mode": "deterministic",
        "input": "pasted_news",
        "steps": [
            "detect_ticker",
            "summarize",
            "extract_claims",
            "classify_event",
            "retrieve_current_thesis",
            "retrieve_assumptions",
            "retrieve_evidence",
            "assess_impact",
            "propose_update",
            "ask_for_approval",
            "save_or_discard",
        ],
    },
    {
        "name": "EarningsWorkflow",
        "implementation_status": "implemented",
        "truth": "POST /run ejecuta EarningsWorkflowService via un wrapper MAF de 2 nodos (load_context + execute); la lista de pasos describe el servicio, no el grafo. EarningsRun persiste running->completed/failed.",
        "execution_mode": "microsoft_agent_framework",
        "input": "ticker + earnings docs",
        "steps": [
            "ingest_earnings_release",
            "extract_reported_numbers",
            "reconcile_SEC/FMP/company_release",
            "compare_vs_previous_period",
            "extract_guidance",
            "analyze_call",
            "update_management_claim_tracker",
            "update_assumptions",
            "rerun_valuation",
            "red_team",
            "source_audit",
            "generate_thesis_diff",
            "save_new_version",
        ],
    },
    {
        "name": "ChatWorkflow",
        "implementation_status": "descriptive",
        "truth": "El chat vive en su propia ruta de API, no en este endpoint de workflows. Langfuse: shadow tracing opcional via run envelope, solo metadatos.",
        "execution_mode": "deterministic_plus_llm_synthesis",
        "input": "user_question",
        "steps": [
            "classify_scope",
            "detect_ticker/company/portfolio",
            "retrieve_structured_data",
            "retrieve_documents",
            "retrieve_latest_thesis",
            "call_python_tools_if_needed",
            "answer_with_sources",
            "propose_actions_if_relevant",
        ],
    },
    {
        "name": "RedTeamWorkflow",
        "implementation_status": "implemented",
        "truth": "POST /run ejecuta RedTeamService (reglas DETERMINISTAS sobre claims/evidencia/valoracion) via wrapper MAF de 2 nodos. No es un agente autonomo: el modo MAF es solo la envoltura del grafo.",
        "execution_mode": "microsoft_agent_framework",
        "input": "ticker",
        "steps": [
            "load_current_thesis",
            "load_supporting_and_contradictory_evidence",
            "check_unsupported_material_claims",
            "compare_ROIC_vs_WACC",
            "analyze_moat_and_peers",
            "attack_assumptions",
            "build_strongest_bear_case",
            "define_falsification_tests",
            "create_review_and_alert",
        ],
    },
    {
        "name": "ContradictionWorkflow",
        "implementation_status": "descriptive",
        "truth": "Los escaneos de contradiccion corren como actors Dramatiq programados; este workflow no tiene ruta de ejecucion en la API.",
        "execution_mode": "deterministic",
        "input": "ticker + document/news",
        "steps": [
            "extract_material_statements",
            "retrieve_similar_historical_claims",
            "classify_relation",
            "apply_source_hierarchy",
            "create_evidence_suggestions",
            "update_claim_state",
            "create_review_and_alert",
        ],
    },
    {
        "name": "DeepResearchWorkflow",
        "implementation_status": "descriptive",
        "truth": "Sin ruta de ejecucion en la API; describe el flujo conceptual.",
        "execution_mode": "microsoft_agent_framework",
        "input": "ticker + research question",
        "steps": [
            "plan_research",
            "retrieve_primary_sources",
            "challenge_source_coverage",
            "synthesize_with_citations",
            "evaluate_answer",
        ],
    },
    {
        "name": "ThesisReviewWorkflow",
        "implementation_status": "descriptive",
        "truth": "Las revisiones de tesis corren via scheduler; este workflow no tiene ruta de ejecucion en la API.",
        "execution_mode": "microsoft_agent_framework",
        "input": "ticker + proposed thesis change",
        "steps": [
            "load_current_thesis",
            "review_evidence_delta",
            "challenge_assumptions",
            "propose_review_decision",
        ],
    },
]
