import Link from 'next/link';
import { ArrowLeft, GitCompare, Plus } from 'lucide-react';

import { MutationForm } from '@/components/forms/MutationForm';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { createDriverAssumption, getDriverAssumptions } from '@/lib/actions/research-tools.actions';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export default async function DriverAssumptionsPage({ params }: { params: Promise<{ ticker: string }> }) {
  const ticker = (await params).ticker.toUpperCase();
  const assumptions = await getDriverAssumptions(ticker);
  const latest = new Map<string, (typeof assumptions)[number]>();
  for (const item of assumptions) latest.set(`${item.driver_key}:${item.fiscal_year}:${item.scenario}`, item);
  const current = [...latest.values()].sort((a, b) => a.driver_key.localeCompare(b.driver_key) || a.fiscal_year - b.fiscal_year || a.scenario.localeCompare(b.scenario));
  return <main className="mx-auto flex max-w-7xl flex-col gap-6"><header className="border-b border-gray-800 pb-5"><Button asChild className="mb-4" size="sm" variant="ghost"><Link href={`/research/${ticker}`}><ArrowLeft className="h-4 w-4" />{ticker} workspace</Link></Button><p className="text-sm font-semibold uppercase text-teal-300">Operating model</p><h1 className="mt-1 text-3xl font-bold text-gray-100">Driver Assumptions</h1><p className="mt-2 text-sm text-gray-400">Editable bear/base/bull overrides. Each change creates a new immutable version and rebuilds the model.</p></header>
    <MutationForm action={createDriverAssumption.bind(null, ticker)} className="rounded-xl border border-gray-800 bg-[#101010] p-5" resetOnSuccess successMessage="Assumption version created"><div className="mb-4 flex items-center gap-2"><Plus className="h-5 w-5 text-teal-300" /><h2 className="font-semibold text-gray-100">New assumption version</h2></div><div className="grid gap-3 md:grid-cols-3"><Input list="driver-keys" name="driver_key" placeholder="Driver key" required /><datalist id="driver-keys">{[...new Set(assumptions.map((item) => item.driver_key))].map((key) => <option key={key} value={key} />)}</datalist><Input min="1900" max="2200" name="fiscal_year" placeholder="Fiscal year" required type="number" /><select className="h-9 rounded-md border border-gray-800 bg-black px-3 text-sm text-gray-200" name="scenario" defaultValue="base"><option value="bear">Bear</option><option value="base">Base</option><option value="bull">Bull</option></select><Input name="value" placeholder="Value" required type="number" step="any" /><Input min="0" max="1" name="confidence" defaultValue="1" required step="0.01" type="number" /><Input name="source" placeholder="Source or analyst override" required /><Textarea className="md:col-span-3" name="rationale" placeholder="Why this assumption is appropriate" required /><Button className="w-fit" type="submit"><Plus className="h-4 w-4" />Create version</Button></div></MutationForm>
    <section className="rounded-xl border border-gray-800 bg-[#101010] p-5"><div className="mb-4 flex items-center gap-2"><GitCompare className="h-5 w-5 text-teal-300" /><h2 className="text-lg font-semibold text-gray-100">Active scenario table</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="text-xs uppercase text-gray-500"><tr><th className="border-b border-gray-800 py-2">Driver</th><th className="border-b border-gray-800 py-2">Year</th><th className="border-b border-gray-800 py-2">Scenario</th><th className="border-b border-gray-800 py-2 text-right">Value</th><th className="border-b border-gray-800 py-2">Source</th><th className="border-b border-gray-800 py-2 text-right">Confidence</th><th className="border-b border-gray-800 py-2">Rationale</th><th className="border-b border-gray-800 py-2">Version</th></tr></thead><tbody>{current.map((item) => <tr className="border-b border-gray-900" key={`${item.driver_key}-${item.fiscal_year}-${item.scenario}`}><td className="py-3 font-semibold text-gray-200">{item.driver_key}</td><td className="py-3 text-gray-300">{item.fiscal_year}</td><td className="py-3"><Badge className={item.scenario === 'bear' ? 'border-red-900 text-red-300' : item.scenario === 'bull' ? 'border-teal-800 text-teal-300' : ''} variant="outline">{item.scenario}</Badge></td><td className="py-3 text-right text-gray-100">{Number(item.value).toLocaleString()}</td><td className="py-3 text-gray-400">{item.source}</td><td className="py-3 text-right text-gray-400">{(Number(item.confidence) * 100).toFixed(0)}%</td><td className="max-w-sm py-3 text-gray-400">{item.rationale}</td><td className="py-3 text-xs text-gray-500">#{item.id}{item.previous_version_id ? ` ← #${item.previous_version_id}` : ''}</td></tr>)}{!current.length ? <tr><td className="py-5 text-gray-500" colSpan={8}>Build the long-term model first, then create driver overrides here.</td></tr> : null}</tbody></table></div></section>
    <details className="rounded-xl border border-gray-800 bg-[#101010] p-5"><summary className="cursor-pointer font-semibold text-gray-200">Version history ({assumptions.length})</summary><div className="mt-4 grid gap-2">{assumptions.slice().reverse().map((item) => <div className="grid gap-2 rounded-lg border border-gray-800 p-3 text-sm md:grid-cols-[1fr_90px_90px_120px_1fr]" key={item.id}><span className="text-gray-200">{item.driver_key}</span><span>{item.fiscal_year}</span><span>{item.scenario}</span><span>{Number(item.value).toLocaleString()}</span><span className="text-gray-500">v#{item.id} · {item.created_at}</span></div>)}</div></details>
  </main>;
}
