import Link from 'next/link';
import { ArrowLeft, RefreshCcw, UploadCloud } from 'lucide-react';

import { MutationForm } from '@/components/forms/MutationForm';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { createManagementPromise, getManagementCredibility, importManagementCallClaims, reconcileManagementCredibility, updateManagementExplanation } from '@/lib/actions/research-tools.actions';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export default async function ManagementCredibilityPage({ params }: { params: Promise<{ ticker: string }> }) {
  const ticker = (await params).ticker.toUpperCase();
  const dashboard = await getManagementCredibility(ticker);
  return <main className="mx-auto flex max-w-7xl flex-col gap-6"><header className="flex flex-col gap-4 border-b border-gray-800 pb-5 lg:flex-row lg:items-end"><div><Button asChild className="mb-4" size="sm" variant="ghost"><Link href={`/research/${ticker}`}><ArrowLeft className="h-4 w-4" />{ticker} workspace</Link></Button><p className="text-sm font-semibold uppercase text-teal-300">Management accountability</p><h1 className="mt-1 text-3xl font-bold text-gray-100">Management Credibility</h1><p className="mt-2 text-sm text-gray-400">Register dated promises and reconcile them against canonical financial facts.</p></div><div className="flex flex-wrap gap-2 lg:ml-auto"><MutationForm action={importManagementCallClaims.bind(null, ticker)} successMessage="Call claims imported"><Button type="submit" variant="outline"><UploadCloud className="h-4 w-4" />Import call claims</Button></MutationForm><MutationForm action={reconcileManagementCredibility.bind(null, ticker)} successMessage="Promises reconciled"><Button type="submit"><RefreshCcw className="h-4 w-4" />Reconcile</Button></MutationForm></div></header>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{[['Score', dashboard.score === null ? 'n/a' : `${(dashboard.score * 100).toFixed(0)}%`], ['Grade', dashboard.grade], ['Open', dashboard.counts.open], ['Met', dashboard.counts.met], ['Partial', dashboard.counts.partial], ['Missed', dashboard.counts.missed]].map(([label, value]) => <div className="rounded-xl border border-gray-800 bg-[#101010] p-4" key={label}><div className="text-xs font-semibold uppercase text-gray-500">{label}</div><div className="mt-2 text-xl font-semibold text-gray-100">{value}</div></div>)}</section>
    <MutationForm action={createManagementPromise.bind(null, ticker)} className="rounded-xl border border-gray-800 bg-[#101010] p-5" resetOnSuccess successMessage="Promise registered"><h2 className="font-semibold text-gray-100">Register a promise</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><Textarea className="md:col-span-3" name="promise" placeholder="Exact management promise or guidance" required /><Input name="promise_date" required type="date" /><Input name="expected_period" placeholder="FY2027 or Q4 2026" required /><Input name="metric" placeholder="Canonical metric (optional)" /><select className="h-9 rounded-md border border-gray-800 bg-black px-3 text-sm text-gray-200" defaultValue="" name="operator"><option value="">Qualitative / no target</option>{['>', '>=', '<', '<=', '=='].map((item) => <option key={item}>{item}</option>)}</select><Input name="target_value" placeholder="Target value" step="any" type="number" /><Input name="unit" placeholder="Unit" /><Input name="source_document_id" placeholder="Source document ID" type="number" min="1" /><Button className="w-fit" type="submit">Register promise</Button></div></MutationForm>
    <section className="grid gap-4">{dashboard.promises.map((promise) => <article className="rounded-xl border border-gray-800 bg-[#101010] p-5" key={promise.id}><div className="flex flex-col gap-3 md:flex-row md:items-start"><div><div className="flex flex-wrap items-center gap-2"><Badge className={promise.status === 'met' ? 'border-teal-800 text-teal-300' : promise.status === 'missed' ? 'border-red-900 text-red-300' : promise.status === 'partial' ? 'border-amber-900 text-amber-300' : ''} variant="outline">{promise.status}</Badge><span className="text-xs text-gray-500">promised {promise.promise_date} · expected {promise.expected_period}</span></div><h2 className="mt-3 font-semibold leading-6 text-gray-100">{promise.promise}</h2></div><div className="rounded-lg border border-gray-800 p-3 text-sm md:ml-auto md:min-w-56"><div className="text-xs uppercase text-gray-500">Target / actual</div><div className="mt-2 text-gray-200">{promise.metric ?? 'qualitative'} {promise.operator ?? ''} {promise.target_value ?? 'n/a'} {promise.unit ?? ''}</div><div className="mt-1 text-teal-300">actual {promise.actual_value ?? 'pending'}</div></div></div><MutationForm action={updateManagementExplanation.bind(null, ticker, promise.id)} className="mt-4 flex flex-col gap-2 md:flex-row" successMessage="Explanation saved"><Input className="flex-1" defaultValue={promise.management_explanation ?? ''} name="explanation" placeholder="Management explanation or analyst context" required /><Button type="submit" variant="outline">Save explanation</Button></MutationForm></article>)}{!dashboard.promises.length ? <div className="rounded-xl border border-dashed border-gray-800 p-8 text-center text-sm text-gray-500">No promises registered yet.</div> : null}</section><p className="text-xs text-gray-500">Method: {dashboard.method}. Results depend on canonical metric mapping and available reported facts.</p>
  </main>;
}
